### ISSUE TITLE
UBitLocations mistake

### ISSUE THREAD

**Issue by project-dev** [KitronikLtd/pxt-kitronik-zip-tile#1]
Hello.
README.md is written to use UBitLocations.Standard.
However, there is no UBitLocations.Standard in the source code.
I want you to correct it.

Translation source：
こんにちは。
README.mdでは UBitLocations.Standard を使うように書かれています。
しかし、ソースコードにはUBitLocations.Standardはありません。
正しい内容に修正してほしいです。

**Comment by KitronikLtd** [comment]
Thanks for noticing the mistake, corrections have now been made.
