### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [KitronikLtd/pxt-kitronik-zip-tile#3]
Hi @KitronikLtd ,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

We're looking into compatibility issues with MicroBitFont, and will track updates in lancaster-university/codal-microbit-v2#31.

```
/home/build/prjclone/pxtapp/pxt-kitronik-zip-tile/zip_tile.cpp:18:1: error: 'MicroBitFont' was not declared in this scope
```

**Comment by KitronikLtd** [comment]
@microbit-sam Please can you check the v3-makecode branch for this repo, as this has the changes we believe are neccessary to be compatible with the CODAL changes?

**Comment by microbit-sam** [comment]
Yep that looks right - apologies for the generic copy-paste issue

I've added a typedef to fix this globally https://github.com/lancaster-university/codal-microbit-v2/pull/32, so if you wish to keep your code as is this should be fixed in the next CODAL tag

**Comment by KitronikLtd** [comment]
Great, thanks!

**Comment by AlasdairAtKitronik** [comment]
@microbit-sam Although I had tested all of this in the beta version of MakeCode V3, now that MakeCode V3 has gone live, this extension no longer seems to be working - when downloading, it just hangs with this screen:
![image](https://user-images.githubusercontent.com/36475405/99790054-77442c80-2b1b-11eb-8641-86c552a5e049.png)

Why would it not be working now, given it was tested and fine in the beta?

**Comment by microbit-sam** [comment]
Could you try recreating this in a new project? I'm not exactly sure what the problem is, but I'm also experiencing some hangs when opening existing projects that use extensions (it isn't just yours)

**Comment by AlasdairAtKitronik** [comment]
I've created several new projects for all the tests I've done, not opening any previous programs.

**Comment by AlasdairAtKitronik** [comment]
@microbit-sam Programs are now compiling for the Tile extension, and I can program a V1 micro:bit, but now I'm getting 
":( E927" scrolling immediately on the V2 display. What is this error?
I don't understand, because I had the Tile working for V2 micro:bit in the /beta editor several weeks ago.

**Comment by microbit-sam** [comment]
E927 is shown for disabled extensions, these are specified by a list, rather than on compile time

I've asked Microsoft to ignore the list for `/beta`, and if you wish to be removed from the list please can you submit an issue to Microsoft (I have no control over the list, sorry)
https://github.com/microsoft/pxt-microbit/issues/new?template=feature_request.md

**Comment by AlasdairAtKitronik** [comment]
@microbit-sam Thanks - issue submitted now.

**Comment by AlasdairAtKitronik** [comment]
ZIP Tile now working correctly with V2 micro:bit
