### ISSUE TITLE
Use with other OEM 8x8 Matrix

### ISSUE THREAD

**Issue by CCERocks** [KitronikLtd/pxt-kitronik-zip-tile#5]
hi, i wonder how can i use this code with other OEM 8x8 Matrix that have different wiring from your ziptile ? 

the led animation / movement when wrong with your code.

regards

**Comment by AlasdairAtKitronik** [comment]
This software is specifically designed to work with the Kitronik ZIP Tile, so it would need modification before it could be used with other matrices that have a different connection setup.
You can take a fork of the repo and edit the code to suit your own setup. I imagine this will involve changing the LED position calculations in the showText functions etc.

This is not something that we would want to undertake ourselves, so I will close this issue.
